//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "outfits")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub pid: Uuid,
    pub name: String,
    pub description: Option<String>,
    pub image_url: Option<String>,
    pub user_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id"
    )]
    Users,
    #[sea_orm(has_many = "super::outfit_clothing::Entity")]
    OutfitClothing,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::outfit_clothing::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OutfitClothing.def()
    }
}

impl Related<super::clothings::Entity> for Entity {
    fn to() -> RelationDef {
        super::outfit_clothing::Relation::Clothings.def()
    }
    
    fn via() -> Option<RelationDef> {
        Some(super::outfit_clothing::Relation::Outfits.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}