//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

pub use super::clothings::Entity as Clothings;
pub use super::outfit_clothing::Entity as OutfitClothing;
pub use super::outfits::Entity as Outfits;
pub use super::users::Entity as Users;
